#PBS -S /bin/bash
#
##PBS -j oe
#
#
##PBS -l nodes=1:ppn=2
#PBS -l walltime=24:00:00
#

. activate caffe-video_triplet
. ~/DevOps/env_scripts/add_cudnn_v3.sh
. ~/DevOps/env_scripts/add_cuda_lib.sh
. ~/DevOps/env_scripts/add_conda_env_lib.sh
. ~/DevOps/env_scripts/add_openblas.sh

export MY_MARGIN_VAL=0.5
export MY_HARD_RATIO=0.5

mkdir -p /home/haonans/capstone/video_models/margin_${MY_MARGIN_VAL}_hard_${MY_HARD_RATIO}/
mkdir -p /home/haonans/capstone/log/margin_${MY_MARGIN_VAL}_hard_${MY_HARD_RATIO}/

cd /home/haonans/capstone/Break12306Captcha/train_triplet/

source train.sh&> /home/haonans/capstone/log/margin_${MY_MARGIN_VAL}_hard_${MY_HARD_RATIO}/training.log
